### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lattewyd** [arnu515/minecraft-servermaker-python#1]
I can't install this thing. The error is:
Traceback (most recent call last):
  File "C:\Users\*******\Desktop\mcservermaker.py", line 79, in <module>
    versionList = getVersions() #Getting the list of paper versions
  File "C:\Users\*****\Desktop\mcservermaker.py", line 22, in getVersions
    versionList = json.loads(versionJson)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
I need help with this.

**Comment by arnu515** [comment]
This is happening because the API in use has been removed. The code no
longer works for now.

**Comment by EnderBender08** [comment]
arnu, why don't you use the official paper api? api.papermc.io

**Comment by arnu515** [comment]
This thing is old, the official paper API didn't exist back then. I'll add a task to rewrite this in my todo list.

**Comment by Cagy-Koala-199763** [comment]
> This thing is old, the official paper API didn't exist back then. I'll add a task to rewrite this in my todo list.

When are you gonna edit it :(
